# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-iPod
version:      0.01
version_from: 
installdirs:  site
requires:
    DBI:                           0
    Mac::iPod::GNUpod:             1
    Package::Base:                 0.01
    SQL::Statement:                1.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
